
import { createServerSupabaseClient } from '@/lib/supabase/server'
import RegistryTable from '@/components/registry/RegistryTable'
import PrintButton from '@/components/registry/PrintButton'
import { redirect } from 'next/navigation'

export default async function InstructorRegistryPage({
  searchParams,
}: {
  searchParams: { date?: string }
}) {
  const supabase = createServerSupabaseClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) redirect('/login')

  // Default to today
  const date = searchParams.date || new Date().toISOString().split('T')[0]

  let registryData: any[] = []

  // Instructor can only see THEIR classes
  const { data, error } = await supabase.rpc('get_class_registry', {
    p_date: date,
    p_program_id: null,
    p_instructor_id: user.id 
  })

  if (error) {
    console.error('Error fetching registry:', error)
  } else {
    registryData = data || []
  }

  return (
    <div className="container mx-auto p-4 max-w-5xl">
      <div className="mb-6 print:hidden flex justify-between items-center bg-gray-50 p-4 rounded-lg">
        <div>
           <h1 className="text-2xl font-bold text-gray-900 dark:text-white">My Class Registry</h1>
           <p className="text-gray-600 dark:text-gray-400">Daily roster for {date}</p>
        </div>
        <div className="flex items-center gap-4">
             {/* Simple Date Picker for Instructor */}
             <form className="flex items-center gap-2">
                 <input 
                    type="date" 
                    name="date" 
                    defaultValue={date}
                    className="border border-gray-300 p-2 rounded-md text-sm focus:border-blue-500 focus:ring-blue-500 dark:bg-gray-800 dark:border-gray-700"
                 />
                 <button type="submit" className="bg-gray-200 text-gray-800 px-3 py-2 rounded-md hover:bg-gray-300 text-sm font-medium">Go</button>
             </form>
             <PrintButton />
        </div>
      </div>

      <div className="bg-white p-6 shadow-sm print:shadow-none print:p-0 min-h-[50vh]">
         {registryData.length === 0 ? (
             <div className="text-center py-12 text-gray-500">
                 No classes scheduled for {date}.
             </div>
         ) : (
             <RegistryTable entries={registryData} />
         )}
      </div>
      
      <div className="hidden print:block fixed bottom-4 left-4 text-xs text-gray-400">
          Generated by Ski School OS on {new Date().toLocaleString()}
      </div>
    </div>
  )
}
